/******************************************************************************
 *                                                                            *
 * Compilar con g++ -o chat chat.cpp -std=c++11 -lfltk                        *
 *                                                                            *
 ******************************************************************************/
 
// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef chat_h
#define chat_h
#include <FL/Fl.H>
#include <FL/Fl_Text_Buffer.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class UserInterface {
  Fl_Text_Buffer * m_Buffer; 
public:
  UserInterface();
  Fl_Double_Window *m_MainWindow;
  Fl_Text_Display *m_Output;
  Fl_Input *m_Input;
  Fl_Button *m_Send;
private:
  inline void cb_m_Send_i(Fl_Button*, void*);
  static void cb_m_Send(Fl_Button*, void*);
public:
  void show(int argc, char ** argv);
};
#endif
